### ISSUE TITLE
Weights of audio sub network always converging towards 0

### ISSUE THREAD

**Issue by purvanshi** [Justin1904/TensorFusionNetworks#5]
The last layer of audio subnetwork (audio_h in model.py file) always updates to a tensor of zeros, which means that audio input has no contribution towards the output. Is this what the implementation should be?

**Comment by Justin1904** [comment]
Can you point me to exactly where the audio is being updated toward zeros values? Sorry I didn't quite figure out that part on my own.

**Comment by purvanshi** [comment]
check out model.py line 135. The output from the audio subnetwork. I tried printing the outputs of all sub networks and found that audio one always updates to zero.

**Comment by Justin1904** [comment]
I guess this is probably because the default hyper parameters sets the dimensions of audio to 4, which limits the expressivity of audio modality, hence the model learns to just ignore it. Try different hyper parameter settings might help. Other than that, I don't see explicit regularization of the audio modality toward zero, so it could be that the audio modality just don't help as much after all.
