### ISSUE TITLE
Old api

### ISSUE THREAD

**Issue by lan-qing** [Justin1904/TensorFusionNetworks#7]
Hi Justin,
It seems that the api [mmsdk](https://github.com/A2Zadeh/CMU-MultimodalSDK) was renewed but the codes here still use the old api. So it cannot be used now. Would you have plans to renew the codes here?

Thank you!

Best Wishes,
Lan-qing

**Comment by Justin1904** [comment]
Hi, we do have plans for updating the code, but as for now the features that we use in TFN is not fully available in the new SDK. We are currently working on making the new SDK support all the features that were available in the past version, and once that is done I'll update the TFN code.

BTW if you are just looking for some model for multi-view data and would like to start using it right away you can also check this repo: https://github.com/Justin1904/Low-rank-Multimodal-Fusion
It is a more recent model we built for multi-view data, and in that repo we provide the datasets in pickle files, independent of the SDK, so that you can simply run the code without worrying about the API changes.

**Comment by lan-qing** [comment]
Thank you!
